version: '3'

services:
  db-user:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db-user'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      demo_net:
        ipv4_address: 172.30.0.2
  spring-demo:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8088:8080"
    environment:
      - DB_IP=db-user
      - DB_PORT=3306
      - DB_DBNAME=db-user
      - DB_USER=root
      - DB_PASSWORD=admin
    networks:
      demo_net:
        ipv4_address: 172.30.0.3

volumes:
  my-db:

networks:
  demo_net:
    external: true
