version: '3'

services:
  db-rabbit:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db-rabbit'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3309:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      demo_net:
        ipv4_address: 172.30.1.2
  spring-demo:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8091:8090"
    environment:
      - DB_IP=db-rabbit
      - DB_PORT=3306
      - DB_DBNAME=db-rabbit
      - DB_USER=root
      - DB_PASSWORD=admin
    networks:
      demo_net:
        ipv4_address: 172.30.1.3

volumes:
  my-db:

networks:
  demo_net:
    external: true
