version: '3'

services:
  db-device:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db-device'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3308:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      demo_net:
        ipv4_address: 172.30.0.4

  spring-demo:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8087:8081"
    environment:
      - DB_IP=db-device
      - DB_PORT=3306
      - DB_DBNAME=db-device
      - DB_USER=root
      - DB_PASSWORD=admin
    networks:
      demo_net:
        ipv4_address: 172.30.0.5

volumes:
  my-db:

networks:
  demo_net:
    external: true
